### ISSUE TITLE
Compilation isn't working for me

### ISSUE THREAD

**Issue by ghost** [jacobwilliams/nlesolver-fortran#22]
Hey, so just as the github page says, I ran the command : 

fpm build --profile release

Yet the compilation goes well until the part 

Depuis https://github.com/jacobwilliams/LSMR
 * tag               1.0.0      -> FETCH_HEAD

After that I get the error : 

<ERROR>*cmd_build*:model error:Key fortran is not allowed in package file
STOP 1

I am using Ubuntu 22.04 and gfortran 11.4.

**Comment by jacobwilliams** [comment]
You need a newer version of FPM. Then it should work.
